# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0004_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='dept',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='orchestration.Department'),
            preserve_default=False,
        ),
    ]
