# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0005_auto_20170822_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dept',
        ),
    ]
