# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='state',
            name='roles',
        ),
        migrations.AddField(
            model_name='project',
            name='roles',
            field=models.ManyToManyField(to='orchestration.Role'),
        ),
        migrations.AddField(
            model_name='role',
            name='states',
            field=models.ManyToManyField(to='orchestration.State'),
        ),
    ]
