# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0002_auto_20170821_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='projectname',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='rolename',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='statename',
        ),
    ]
