# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0003_auto_20170821_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=100)),
                ('projects', models.ManyToManyField(to='orchestration.Project')),
            ],
        ),
    ]
