# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0005_remove_department_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orchestration.Department'),
            preserve_default=False,
        ),
    ]
