# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0009_auto_20170901_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodename', models.CharField(max_length=100)),
                ('projectname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestration.Project')),
                ('rolename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestration.Role')),
            ],
        ),
    ]
