# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0010_nodes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nodes',
            new_name='Node',
        ),
    ]
