# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0011_auto_20170905_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
