# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0014_role_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='rolename',
        ),
        migrations.AddField(
            model_name='node',
            name='roles',
            field=models.ManyToManyField(to='orchestration.Role'),
        ),
    ]
