# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0016_state_statefunctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='owner',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
