# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0018_auto_20170907_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='roles',
        ),
    ]
