# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0020_auto_20170907_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
